### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by bluchip** [anseki/plain-modal#2] opened 2019-10-02 09:45 UTC
Hello,

I have the following weird issue. After a PlainModal is displayed in my application then if Itype something in the application, in  an input for example or just generally type something the followeing message is displayed "Uncaught TypeError: Cannot read property 'toLowerCase' of undefined". It happens eveyrtime and on everypage just after a PlainModal is displayed. I am using PlainModal for bootstrap. If page is reloaded then al is ok. Other than the message its not causing any other issues. 

Other than that great work by the way.

**Comment by anseki** [comment] 2019-10-02 10:23
Hi @bluchip, thank you for the comment.
* Could you tell me your environment? (OS, Name and version of web browser)
* For a test, try to set [`PlainModal.closeByEscKey = false`](https://anseki.github.io/plain-modal/#plainmodalclosebyesckey).

**Comment by bluchip** [comment] 2019-10-02 12:57
Hi again,

Its actually a little complicated project. The browser is Chronium engine wrapped in a Java application (JXBRowser is the java component that I am using). Basically its my own browser using the Chronium engine. OS is Windows 10 but I think this is relevant. 

I tried to use the setting you suggested but no luck. Actually even if I dont set it the modal does not close with esc key.

**Comment by anseki** [comment] 2019-10-02 15:03
The JxBrowser is using Blink browser engine, and Google Chrome and Chromium (not "Chronium") web browsers also are using the Blink browser engine.

So, could you give me a concrete explanation about the "no luck"?
Please understand that the result is important, because that is a test as I said, it's not a solution.

**Comment by bluchip** [comment] 2019-10-02 16:12
Hello again,

So I open my modal like below

cancel_modal = new PlainModal(document.getElementById('cancel_modal'), {
            duration: 50
        });
        cancel_modal.open();

Like this if I press the escape button the modal is not closing. 

If I do your test
cancel_modal = new PlainModal(document.getElementById('cancel_modal'), {
            duration: 50,
            closeByEscKey: false
        });
        cancel_modal.open();

still not closing with escape key. Even if I set closeByEscKey: true still modal wont close.

In every case as soon as the modal appears I get the error I described everytime I press any button in the window.

Thanks

**Comment by anseki** [comment] 2019-10-02 16:54
Your code is wrong.
The `closeByEscKey` is not option. It is static property.
See document: https://anseki.github.io/plain-modal/#plainmodalclosebyesckey
You have to insert this line into top of your code.
```js
PlainModal.closeByEscKey = false;
```

**Comment by bluchip** [comment] 2019-10-02 17:01
Hi,

I set the code like you said and I am not getting the error anymore. If I set it to true I get the error. In any case the modal is not closing when I hit escape. 

But you test PlainModal.closeByEscKey = false; is not displaying the error.

**Comment by anseki** [comment] 2019-10-03 00:26
That result means that an `Event` object is broken for some reason or other.
Your code or another library might have a problem.
To reproduce the issue, could you indicate an example?
By using for example JSFiddle like this:
https://jsfiddle.net/9he375j0/ (Click "Open" button)

**Comment by anseki** [comment] 2019-10-12 03:15
No reply came, then I close this abandoned issue.

**Closed by anseki** 2019-10-12 03:15 UTC
